In [1]:
import numpy as np

# 創建一個包含10個零的陣列

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 創建一個包含10個1的陣列

In [11]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])