In [1]:
import numpy as np

# 創建一個包含10個零的陣列

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 創建一個包含10個1的陣列

In [4]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# 創建一個包含10個5的陣列

In [6]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 創建一個包含從10到50的整數的陣列

In [7]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# 要創建一個包含從10到50的所有偶數整數的陣列

# 要創建一個3x3矩陣，其中包含從0到8的值

 # NumPy 生成一個包含25個從標準正態分布的亂數