In [1]:
import numpy as np

# 要創建一個包含從10到50的所有偶數整數的陣列

In [2]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [5]:
np.arange(10,51)[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# 要創建一個3x3矩陣，其中包含從0到8的值


In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

 # NumPy 生成一個包含25個從標準正態分布的亂數

In [18]:
np.random.randn(25)

array([ 0.17134631, -2.16048511, -0.07121158, -1.06981054, -0.48194685,
       -1.70254059,  1.06009251,  0.79108498,  1.04799625, -0.26578312,
       -0.76981683, -0.86947139,  0.71636497,  1.05374858,  0.18085555,
       -0.58065413,  0.301339  , -0.62298636,  0.12624664, -0.73418972,
        1.36648958, -2.36498351,  0.07255102, -0.00816997,  1.05466669])

#### 要創建一個包含從0到1之間20個等距點的陣列

In [19]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

In [20]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## 希望輸出的樣式如下
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [21]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## 根據以下輸出取值
```python
array([[ 2],
       [ 7],
       [12]])


In [42]:
mat[:3,1:2]


array([[ 2],
       [ 7],
       [12]])

In [44]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
mat[2:,1:3]

array([[12, 13],
       [17, 18],
       [22, 23]])

# Pandas

In [47]:
import pandas as pd

In [58]:
myindex = ['USA','Canada','Mexico']
mydata = [1776,1867,1821]
myser = pd.Series(mydata,index = myindex)
myser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [59]:
import numpy as np
ran_data = np.random.randint(0,100,4)
names = ['Andrew','Bobo','Claire','David']
s2 = pd.Series(ran_data,names)
print(s2)

Andrew    57
Bobo      48
Claire    99
David     89
dtype: int32


In [68]:
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}
s1_q1 = pd.Series(q1)
s2_q2 = pd.Series(q2)
print(s1_q1)
print(s2_q2)

print(s1_q1["Japan"])
try:
    print(s1_q1["Brazil"])
except:
    print("Brazil Error")   

Japan     80
China    450
India    200
USA      250
dtype: int64
Brazil    100
China     500
India     210
USA       260
dtype: int64
80
Brazil Error


## DataFrame

In [83]:
import pandas as pd
import numpy as np
np.random.seed(101)
myData = np.random.randint(0,101,(4,3))
myData

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [85]:
myindex = ['CA','NY','AZ','TX']
mycolumns = ['Jan','Feb','Mar']
df = pd.DataFrame(data = myData)
print(df)


    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63


In [91]:
df = pd.DataFrame(data=myData,index = myindex)
df

0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63

In [103]:
df = pd.DataFrame(data=myData,index = myindex,columns = mycolumns)
df

Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


In [97]:
df.describe()

Jan        Feb        Mar
count   4.000000   4.000000   4.000000
mean   70.000000  21.750000  77.000000
std    22.730303  27.657127  10.198039
min    40.000000   4.000000  63.000000
25%    62.500000   7.750000  73.500000
50%    72.500000  10.000000  79.000000
75%    80.000000  24.000000  82.500000
max    95.000000  63.000000  87.000000

  ## 可能需要安裝以下套件
  conda install xlrd
    
  conda install openpyxl


In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("tips.csv")
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [5]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [6]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [8]:
df.head(3)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458

In [11]:
df.tail(3)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  
241       Keith Wong  6011891618747196    Sat3880  
242     Dennis Dixon     4375220550950      Sat17  
243  Michelle Hardin  3511451626698139    Thur672

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [13]:
len(df)

244

In [14]:
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [16]:
df.describe().transpose()

count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00   
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00   
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00   
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00   
CC Number         244.0  2.563496e+15  2.369340e+15  6.040679e+10   

                           25%           50%           75%           max  
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01  
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01  
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00  
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01  
CC Number         3.040731e+13  3.525318e+15  4.553675e+15  6.596454e+15

In [17]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [20]:
myData = df["total_bill"]
print(type(myData))
myData

<class 'pandas.core.series.Series'>


0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [25]:
dfx = df[["total_bill",'tip']]
print(type(dfx))
dfx

<class 'pandas.core.frame.DataFrame'>


total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [40]:
df['tip_percent'] = 100 * df['tip'] / df['total_bill']

In [41]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2          8.495000   
1         10.34  1.66    Male     No   Sun  Dinner     3          3.446667   
2         21.01  3.50    Male     No   Sun  Dinner     3          7.003333   
3         23.68  3.31    Male     No   Sun  Dinner     2         11.840000   
4         24.59  3.61  Female     No   Sun  Dinner     4          6.147500   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3          9.676667   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         13.590000   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         11.335000   
242       17.82  1.75    Male     No   Sat  Dinner     2          8.910000   
243       18.78  3.00  Female     No  Thur  Dinner     2          9.390000   

             Payer Name         CC Number Payment ID  tip_percent  
0    Christy Cunningham  3560325168603410    Sun2959     5.944673  
1        Douglas Tucker  4478071379779230    Sun4608    16.054159  
2        Travis Walters  6011812112971322    Sun4458    16.658734  
3      Nathaniel Harris  4676137647685994    Sun5260    13.978041  
4          Tonya Carter  4832732618637221    Sun2251    14.680765  
..                  ...               ...        ...          ...  
239       Michael Avila  5296068606052842    Sat2657    20.392697  
240      Monica Sanders  3506806155565404    Sat1766     7.358352  
241          Keith Wong  6011891618747196    Sat3880     8.822232  
242        Dennis Dixon     4375220550950      Sat17     9.820426  
243     Michelle Hardin  3511451626698139    Thur672    15.974441  

[244 rows x 12 columns]

In [42]:
df['price_per_person'] = df['total_bill'] / df['size']


In [43]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2          8.495000   
1       10.34  1.66    Male     No  Sun  Dinner     3          3.446667   
2       21.01  3.50    Male     No  Sun  Dinner     3          7.003333   
3       23.68  3.31    Male     No  Sun  Dinner     2         11.840000   
4       24.59  3.61  Female     No  Sun  Dinner     4          6.147500   

           Payer Name         CC Number Payment ID  tip_percent  
0  Christy Cunningham  3560325168603410    Sun2959     5.944673  
1      Douglas Tucker  4478071379779230    Sun4608    16.054159  
2      Travis Walters  6011812112971322    Sun4458    16.658734  
3    Nathaniel Harris  4676137647685994    Sun5260    13.978041  
4        Tonya Carter  4832732618637221    Sun2251    14.680765

In [44]:
df['price_per_person'] = np.round(df['price_per_person'],2)

In [45]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  tip_percent  
0  Christy Cunningham  3560325168603410    Sun2959     5.944673  
1      Douglas Tucker  4478071379779230    Sun4608    16.054159  
2      Travis Walters  6011812112971322    Sun4458    16.658734  
3    Nathaniel Harris  4676137647685994    Sun5260    13.978041  
4        Tonya Carter  4832732618637221    Sun2251    14.680765

|    | C1 | C2 | C3 |
|----|----|----|----|
| A  |  1 |  2 |  3 |
| B  |  4 |  5 |  6 |
| C  |  7 |  8 |  9 |

A B C 表示軸0

C1 C2 C3表示軸1

In [46]:
df = df.drop("tip_percent",axis=1)

In [60]:
df

Payment ID  total_bill   tip     sex smoker   day    time  size  \
0      Sun2959       16.99  1.01  Female     No   Sun  Dinner     2   
1      Sun4608       10.34  1.66    Male     No   Sun  Dinner     3   
2      Sun4458       21.01  3.50    Male     No   Sun  Dinner     3   
3      Sun5260       23.68  3.31    Male     No   Sun  Dinner     2   
4      Sun2251       24.59  3.61  Female     No   Sun  Dinner     4   
..         ...         ...   ...     ...    ...   ...     ...   ...   
239    Sat2657       29.03  5.92    Male     No   Sat  Dinner     3   
240    Sat1766       27.18  2.00  Female    Yes   Sat  Dinner     2   
241    Sat3880       22.67  2.00    Male    Yes   Sat  Dinner     2   
242      Sat17       17.82  1.75    Male     No   Sat  Dinner     2   
243    Thur672       18.78  3.00  Female     No  Thur  Dinner     2   

     price_per_person          Payer Name         CC Number  
0                8.49  Christy Cunningham  3560325168603410  
1                3.45      Douglas Tucker  4478071379779230  
2                7.00      Travis Walters  6011812112971322  
3               11.84    Nathaniel Harris  4676137647685994  
4                6.15        Tonya Carter  4832732618637221  
..                ...                 ...               ...  
239              9.68       Michael Avila  5296068606052842  
240             13.59      Monica Sanders  3506806155565404  
241             11.34          Keith Wong  6011891618747196  
242              8.91        Dennis Dixon     4375220550950  
243              9.39     Michelle Hardin  3511451626698139  

[244 rows x 11 columns]

In [61]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [62]:
df.set_index('Payment ID',inplace=True)
df

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  
Thur672                 9.39     Michelle Hardin  3511451626698139  

[244 rows x 10 columns]

In [64]:
df.index

Index(['Sun2959', 'Sun4608', 'Sun4458', 'Sun5260', 'Sun2251', 'Sun9679',
       'Sun5985', 'Sun8157', 'Sun6820', 'Sun3775',
       ...
       'Sat7220', 'Sat4615', 'Sat5032', 'Sat2929', 'Sat9777', 'Sat2657',
       'Sat1766', 'Sat3880', 'Sat17', 'Thur672'],
      dtype='object', name='Payment ID', length=244)

In [66]:
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221

In [65]:
df.iloc[0]

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [67]:
df.loc["Sun4608"]

total_bill                     10.34
tip                             1.66
sex                             Male
smoker                            No
day                              Sun
time                          Dinner
size                               3
price_per_person                3.45
Payer Name            Douglas Tucker
CC Number           4478071379779230
Name: Sun4608, dtype: object

In [69]:
df.iloc[0:4,2:8]

sex smoker  day    time  size  price_per_person
Payment ID                                                    
Sun2959     Female     No  Sun  Dinner     2              8.49
Sun4608       Male     No  Sun  Dinner     3              3.45
Sun4458       Male     No  Sun  Dinner     3              7.00
Sun5260       Male     No  Sun  Dinner     2             11.84

In [77]:
df.loc["Sun4608":"Sun5260","time":"price_per_person"]

time  size  price_per_person
Payment ID                                
Sun4608     Dinner     3              3.45
Sun4458     Dinner     3              7.00
Sun5260     Dinner     2             11.84

In [72]:
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221

In [73]:
df.drop("Sun2959",axis=0).head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No  Sun  Dinner     4   

            price_per_person        Payer Name         CC Number  
Payment ID                                                        
Sun4608                 3.45    Douglas Tucker  4478071379779230  
Sun4458                 7.00    Travis Walters  6011812112971322  
Sun5260                11.84  Nathaniel Harris  4676137647685994  
Sun2251                 6.15      Tonya Carter  4832732618637221  
Sun9679                 6.32        Erik Smith   213140353657882

In [76]:
#df.drop(0,axis=0).head()

In [78]:
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221

In [79]:
one_row = df.iloc[0]
one_row

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [80]:
df.tail()

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person       Payer Name         CC Number  
Payment ID                                                       
Sat2657                 9.68    Michael Avila  5296068606052842  
Sat1766                13.59   Monica Sanders  3506806155565404  
Sat3880                11.34       Keith Wong  6011891618747196  
Sat17                   8.91     Dennis Dixon     4375220550950  
Thur672                 9.39  Michelle Hardin  3511451626698139

In [95]:
one_row_df = one_row.to_frame().T #transpose()
print(one_row_df)
pd.concat([df,one_row_df])

        total_bill   tip     sex smoker  day    time size price_per_person  \
Sun2959      16.99  1.01  Female     No  Sun  Dinner    2             8.49   

                 Payer Name         CC Number  
Sun2959  Christy Cunningham  3560325168603410  


total_bill   tip     sex smoker   day    time size price_per_person  \
Sun2959      16.99  1.01  Female     No   Sun  Dinner    2             8.49   
Sun4608      10.34  1.66    Male     No   Sun  Dinner    3             3.45   
Sun4458      21.01   3.5    Male     No   Sun  Dinner    3              7.0   
Sun5260      23.68  3.31    Male     No   Sun  Dinner    2            11.84   
Sun2251      24.59  3.61  Female     No   Sun  Dinner    4             6.15   
...            ...   ...     ...    ...   ...     ...  ...              ...   
Sat1766      27.18   2.0  Female    Yes   Sat  Dinner    2            13.59   
Sat3880      22.67   2.0    Male    Yes   Sat  Dinner    2            11.34   
Sat17        17.82  1.75    Male     No   Sat  Dinner    2             8.91   
Thur672      18.78   3.0  Female     No  Thur  Dinner    2             9.39   
Sun2959      16.99  1.01  Female     No   Sun  Dinner    2             8.49   

                 Payer Name         CC Number  
Sun2959  Christy Cunningham  3560325168603410  
Sun4608      Douglas Tucker  4478071379779230  
Sun4458      Travis Walters  6011812112971322  
Sun5260    Nathaniel Harris  4676137647685994  
Sun2251        Tonya Carter  4832732618637221  
...                     ...               ...  
Sat1766      Monica Sanders  3506806155565404  
Sat3880          Keith Wong  6011891618747196  
Sat17          Dennis Dixon     4375220550950  
Thur672     Michelle Hardin  3511451626698139  
Sun2959  Christy Cunningham  3560325168603410  

[245 rows x 10 columns]

# Conditional Filtering

In [94]:
import numpy as np
import pandas as pd

In [96]:
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221

In [99]:
bool_series =  df["total_bill"] > 30
df[bool_series].head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun6686          35.26  5.00  Female     No  Sun  Dinner     4   
Sat239           39.42  7.58    Male     No  Sat  Dinner     4   
Sat6373          31.27  5.00    Male     No  Sat  Dinner     3   
Sun2274          30.40  5.60    Male     No  Sun  Dinner     4   
Sun9677          32.40  6.00    Male     No  Sun  Dinner     4   

            price_per_person         Payer Name         CC Number  
Payment ID                                                         
Sun6686                 8.82       Diane Macias  4577817359320969  
Sat239                  9.86     Lance Peterson  3542584061609808  
Sat6373                10.42  Mr. Brandon Berry  6011525851069856  
Sun2274                 7.60        Todd Cooper      503846761263  
Sun9677                 8.10       James Barnes  3552002592874186

In [101]:
df[df["total_bill"] > 30].head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun6686          35.26  5.00  Female     No  Sun  Dinner     4   
Sat239           39.42  7.58    Male     No  Sat  Dinner     4   
Sat6373          31.27  5.00    Male     No  Sat  Dinner     3   
Sun2274          30.40  5.60    Male     No  Sun  Dinner     4   
Sun9677          32.40  6.00    Male     No  Sun  Dinner     4   

            price_per_person         Payer Name         CC Number  
Payment ID                                                         
Sun6686                 8.82       Diane Macias  4577817359320969  
Sat239                  9.86     Lance Peterson  3542584061609808  
Sat6373                10.42  Mr. Brandon Berry  6011525851069856  
Sun2274                 7.60        Todd Cooper      503846761263  
Sun9677                 8.10       James Barnes  3552002592874186

In [106]:
df[df['sex'] == 'Male'][0:5]

total_bill   tip   sex smoker  day    time  size  \
Payment ID                                                     
Sun4608          10.34  1.66  Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50  Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31  Male     No  Sun  Dinner     2   
Sun9679          25.29  4.71  Male     No  Sun  Dinner     4   
Sun5985           8.77  2.00  Male     No  Sun  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun9679                 6.32          Erik Smith   213140353657882  
Sun5985                 4.38  Kristopher Johnson  2223727524230344

In [132]:
df[(df["total_bill"] > 30) & (df["sex"] == "Male") ].head()

total_bill   tip   sex smoker  day    time  size  \
Payment ID                                                     
Sat239           39.42  7.58  Male     No  Sat  Dinner     4   
Sat6373          31.27  5.00  Male     No  Sat  Dinner     3   
Sun2274          30.40  5.60  Male     No  Sun  Dinner     4   
Sun9677          32.40  6.00  Male     No  Sun  Dinner     4   
Sat8903          38.01  3.00  Male    Yes  Sat  Dinner     4   

            price_per_person             Payer Name         CC Number  
Payment ID                                                             
Sat239                  9.86         Lance Peterson  3542584061609808  
Sat6373                10.42      Mr. Brandon Berry  6011525851069856  
Sun2274                 7.60            Todd Cooper      503846761263  
Sun9677                 8.10           James Barnes  3552002592874186  
Sat8903                 9.50  James Christensen DDS   349793629453226

In [117]:
df[(df["day"] == "Sun") | (df["day"] == "Sat")]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
...                ...   ...     ...    ...  ...     ...   ...   
Sat9777          35.83  4.67  Female     No  Sat  Dinner     3   
Sat2657          29.03  5.92    Male     No  Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes  Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes  Sat  Dinner     2   
Sat17            17.82  1.75    Male     No  Sat  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat9777                11.94      Kimberly Crane      676184013727  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  

[163 rows x 10 columns]

In [143]:
sex = "Female"
df.query(f'total_bill > 30 and sex == "{sex}"' )

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun6686          35.26  5.00  Female     No   Sun  Dinner     4   
Sun6165          34.81  5.20  Female     No   Sun  Dinner     4   
Thur7972         34.83  5.17  Female     No  Thur   Lunch     4   
Sat6240          44.30  2.50  Female    Yes   Sat  Dinner     3   
Thur9313         43.11  5.00  Female    Yes  Thur   Lunch     4   
Sat8863          30.14  3.09  Female    Yes   Sat  Dinner     4   
Sat9777          35.83  4.67  Female     No   Sat  Dinner     3   

            price_per_person      Payer Name         CC Number  
Payment ID                                                      
Sun6686                 8.82    Diane Macias  4577817359320969  
Sun6165                 8.70    Emily Daniel  4291280793094374  
Thur7972                8.71     Shawna Cook  6011787464177340  
Sat6240                14.77   Heather Cohen   379771118886604  
Thur9313               10.78     Brooke Soto  5544902205760175  
Sat8863                 7.54    Shelby House      502097403252  
Sat9777                11.94  Kimberly Crane      676184013727

In [147]:
df.query("day=='Sun' or day=='Sat'")

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
...                ...   ...     ...    ...  ...     ...   ...   
Sat9777          35.83  4.67  Female     No  Sat  Dinner     3   
Sat2657          29.03  5.92    Male     No  Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes  Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes  Sat  Dinner     2   
Sat17            17.82  1.75    Male     No  Sat  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat9777                11.94      Kimberly Crane      676184013727  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  

[163 rows x 10 columns]

In [148]:
df[(df["total_bill"] > 30) & (df["sex"] != "Male") ].head()

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun6686          35.26  5.00  Female     No   Sun  Dinner     4   
Sun6165          34.81  5.20  Female     No   Sun  Dinner     4   
Thur7972         34.83  5.17  Female     No  Thur   Lunch     4   
Sat6240          44.30  2.50  Female    Yes   Sat  Dinner     3   
Thur9313         43.11  5.00  Female    Yes  Thur   Lunch     4   

            price_per_person     Payer Name         CC Number  
Payment ID                                                     
Sun6686                 8.82   Diane Macias  4577817359320969  
Sun6165                 8.70   Emily Daniel  4291280793094374  
Thur7972                8.71    Shawna Cook  6011787464177340  
Sat6240                14.77  Heather Cohen   379771118886604  
Thur9313               10.78    Brooke Soto  5544902205760175

In [149]:
df[(df["total_bill"] > 30) & ~(df["sex"] == "Male") ].head()

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun6686          35.26  5.00  Female     No   Sun  Dinner     4   
Sun6165          34.81  5.20  Female     No   Sun  Dinner     4   
Thur7972         34.83  5.17  Female     No  Thur   Lunch     4   
Sat6240          44.30  2.50  Female    Yes   Sat  Dinner     3   
Thur9313         43.11  5.00  Female    Yes  Thur   Lunch     4   

            price_per_person     Payer Name         CC Number  
Payment ID                                                     
Sun6686                 8.82   Diane Macias  4577817359320969  
Sun6165                 8.70   Emily Daniel  4291280793094374  
Thur7972                8.71    Shawna Cook  6011787464177340  
Sat6240                14.77  Heather Cohen   379771118886604  
Thur9313               10.78    Brooke Soto  5544902205760175

In [150]:
df.query("total_bill >30 and not sex == 'Male'").head()

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun6686          35.26  5.00  Female     No   Sun  Dinner     4   
Sun6165          34.81  5.20  Female     No   Sun  Dinner     4   
Thur7972         34.83  5.17  Female     No  Thur   Lunch     4   
Sat6240          44.30  2.50  Female    Yes   Sat  Dinner     3   
Thur9313         43.11  5.00  Female    Yes  Thur   Lunch     4   

            price_per_person     Payer Name         CC Number  
Payment ID                                                     
Sun6686                 8.82   Diane Macias  4577817359320969  
Sun6165                 8.70   Emily Daniel  4291280793094374  
Thur7972                8.71    Shawna Cook  6011787464177340  
Sat6240                14.77  Heather Cohen   379771118886604  
Thur9313               10.78    Brooke Soto  5544902205760175

In [152]:
option = ["Sun","Sat","Thur"]
df[df["day"].isin(option)]

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  
Thur672                 9.39     Michelle Hardin  3511451626698139  

[225 rows x 10 columns]